# Generated by Django 6.1.1 on 2026-09-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Dono'), ('MANAGER', 'Gerente'), ('STAFF', 'Funcionário')], default='STAFF', max_length=20),
        ),
    ]
