# Generated by Django 6.1.1 on 2026-09-23 18:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_address_options_alter_business_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='confirmation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
