# Generated by Django 6.1.1 on 2026-09-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_out_for_delivery_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatushistory',
            name='delivery_confirmed_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
