# Generated by Django 6.1.1 on 2026-09-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_orderstatushistory_delivery_confirmed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_confirmed_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
