# Generated by Django 5.2.18 on 2026-10-09 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_order_address_order_checkout_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='pix_key',
            field=models.CharField(blank=True, max_length=140, verbose_name='Chave Pix'),
        ),
        migrations.AddField(
            model_name='business',
            name='pix_recipient',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome do recebedor Pix'),
        ),
        migrations.AddField(
            model_name='customer',
            name='normalized_phone',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='address_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='cash_change_for',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Troco para'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDENTE', 'Pagamento pendente'), ('PAGO', 'Pagamento recebido')], default='PENDENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pagamento pendente'), ('PAGO', 'Pagamento recebido')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_events', to='core.order')),
            ],
            options={
                'verbose_name': 'Registro de pagamento',
                'verbose_name_plural': 'Registros de pagamento',
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
