# Generated by Django 6.1.1 on 2026-10-02 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_comanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.comanda'),
        ),
    ]
