# Generated by Django 5.2.18 on 2026-10-09 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_backfill_order_customer_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taxa fixa de entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taxa de entrega do pedido'),
        ),
    ]
