# Generated by Django 6.1.1 on 2026-10-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_order_order_type_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='service_charge_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='service_charge_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
