# Generated by Django 6.1.1 on 2026-10-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_business_service_charge_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_charge_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='service_charge_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
