# Generated by Django 6.1.1 on 2026-10-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_order_service_charge_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa de entrega'),
        ),
        migrations.AddField(
            model_name='business',
            name='pix_key',
            field=models.CharField(blank=True, max_length=140, verbose_name='Chave Pix'),
        ),
        migrations.AddField(
            model_name='business',
            name='pix_recipient',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome do recebedor Pix'),
        ),
    ]
