# Generated by Django 6.1.1 on 2026-10-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_business_delivery_fee_business_pix_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa de entrega'),
        ),
    ]
