# Generated by Django 6.1.1 on 2026-10-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_order_address_order_address_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDENTE', 'Pagamento pendente'), ('PAGO', 'Pagamento recebido')], default='PENDENTE', max_length=20),
        ),
    ]
