# Generated by Django 6.1.1 on 2026-10-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=10),
        ),
    ]
